export const QUOTES = [
    {
        id: 0,
        quote: 'No conozco ningún hecho más alentador que la incuestionable capacidad del hombre para dignificar su vida por medio del esfuerzo consciente',
        author: 'Thoreau, Henry David',
        authorAvatar: require('../assets/Avatar-Thoreau.jpg'),
        bookName: 'Los siete hábitos de la gente altamente efectiva',
        isbn: '978-950-12-5111-1',
        editionPlace: 'Buenos Aires',
        publisher: 'Paidos',
        year: '2007',
        page: '80',
        url: '',
        language: 'es',
        tags: ['proactividad', 'esfuerzo'],
        favorite: false
    },
    {
        id: 1,
        quote: 'No hay en el mundo un triunfo verdadero que pueda separarse de la dignidad en el vivir',
        author: 'Starr Jordan, David',
        bookName: 'Los siete hábitos de la gente altamente efectiva',
        isbn: '978-950-12-5111-1',
        editionPlace: 'Buenos Aires',
        publisher: 'Paidos',
        year: '2007',
        page: '80',
        url: '',
        language: 'es',
        tags: ['dignidad'],
        favorite: true
    },
    {
        id: 2,
        quote: 'La mejor custodia de un hombre es su propia conciencia',
        author: 'Illia, Arturo Humberto',
        bookName: '',
        isbn: '',
        editionPlace: '',
        publisher: '',
        year: '',
        page: '',
        url: '',
        language: 'es',
        tags: ['conciencia'],
        favorite: true
    },
    {
        id: 3,
        quote: 'En la panza se mezcla todo',
        author: 'Brustolon, Carlos Mateo',
        bookName: '',
        isbn: '',
        editionPlace: '',
        publisher: '',
        year: '',
        page: '',
        url: '',
        language: 'es',
        tags: ['vida'],
        favorite: true
    }
];